Fixed a bug with critical error on "0" exitcode
There was a critical error when exitcodes are set in config file:

Normal: Unknown exitcode "0" with Modify on [...]
Error: Critical exitcode.

Variable "rc" on the moment of "Normal: Unknown exitcode" was "(nil)"